In [1]:
# Import packages
import pandas as pd
import numpy as np

In [3]:
# A numpy array
arr = np.random.randn(4) # random values from std normal distribution
print(type(arr))
print(arr, "\n")

# A pandas series made from the previous array
s = pd.Series(arr)
print(type(s))
print(s)

<class 'numpy.ndarray'>
[-0.8824279  -2.04291899 -1.06989469  0.95285488]

<class 'pandas.core.series.Series'>
0   -0.882428
1   -2.042919
2   -1.069895
3    0.952855
dtype: float64

In [7]:
# Example: Creating a pandas.Series from a NumPy array. 
pd.Series(np.arange(3), index = [2023, 2024, 2025])

2023    0
2024    1
2025    2
dtype: int64

In [8]:
# Series with NAs in it
s = pd.Series([1, 2, np.nan, 4, np.nan])
s

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64

In [10]:
# Check In #1
s = pd.Series([1, 2, -999, -999], index = ['A', 'B', 'C', 'D'])
print(s)

A      1
B      2
C   -999
D   -999
dtype: int64

In [16]:
# Check in #2 
s = s.mask(s < 0)
print(s)

A    1.0
B    2.0
C    NaN
D    NaN
dtype: float64

In [41]:
# Initialize dictionary with columns' data 
d = {'col_name_1' : pd.Series(np.arange(3)),
     'col_name_2' : pd.Series([3.1, 3.2, 3.3]),
     }

# Create data frame
df = pd.DataFrame(d)
df

   col_name_1  col_name_2
0           0         3.1
1           1         3.2
2           2         3.3

In [43]:
df.index = ['a', 'b', 'c']

In [45]:
df

   col_name_1  col_name_2
a           0         3.1
b           1         3.2
c           2         3.3

In [47]:
df.columns = ['C1', 'C2']

In [48]:
df

   C1   C2
a   0  3.1
b   1  3.2
c   2  3.3